//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyCaseRPl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PublicationDate { get; set; }
        public string ISBN { get; set; }
        public string Coverimage { get; set; }
        public Nullable<decimal> Pricce { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
